#!/bin/bash

# SSH keys need to be loaded into an agent for Git to use them without
# prompting you for the passphrase every time.

# When you start your VS Code session in the browser, open the terminal
# and run these commands once per session

# The paths to the ssh keys are based off the linuxserver/openvscode-server
# Dockerfile setup and a volume mount of /config/.ssh
# such as: -v ${SSH_DIR}:/config/.ssh:ro

# If your keys are named differnetly then use symlinks or modify this script.

# start ssh-agent if not already running
eval "$(ssh-agent -s)"

# add the github authentication key (you'll be prompted for the passphrase)
ssh-add /config/.ssh/github-authentication

# add the github signing key (you'll be prompted for the passphrase)
ssh-add /config/.ssh/github-signing

# verify the keys are loaded
ssh-add -l

echo "Pau. Have a great day! 🏄 🌈 🌴 🌺 🦄"
