#!/bin/bash

# start ssh-agent if not already running
eval "$(ssh-agent -s)"

# add the github authentication key (you'll be prompted for the passphrase)
ssh-add ~/.ssh/github-authentication

# add the github signing key (you'll be prompted for the passphrase)
ssh-add ~/.ssh/github-signing

# verify the key is loaded
ssh-add -l

echo "Pau. Have a great day! 🏄 🌈 🌴 🌺 🦄"
