name: Lint

on:
  push:
    branches: [main, "develop"]
  pull_request:
    branches: [main]

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          # Use an explicit include list to avoid mixed include/exclude configuration errors
          VALIDATE: "json,yaml,markdown,shell"
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
